### ISSUE TITLE
Only run DeviceTreeCheck if scripts/dts updated

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/ci-tools#76]
PR #73 added DeviceTreeCheck, we need to improve the handling so this only runs on PRs that impact scripts/dts/

**Comment by ulfalizer** [comment]
I think this is counter-productive.

Ideally, you would just run all tests for all PRs, because it's the simplest and most fool-proof thing to do, but unfortunately it makes the tests too slow. To work around that, we check what parts of the code each PR touches and only test those parts. That's more complex and not as fool-proof, but the performance win makes it worth it.

`DeviceTreeCheck` runs in a fraction of a second (less than 0.1 seconds on my system), so the performance argument isn't relevant for it. The win from keeping the test simple and fool-proof is much greater than the win from shaving off that fraction of a second.

We need to remember why things were done in a certain way in the first place, and seeing if those reasons apply, rather than just pattern-matching.

**Comment by marc-hb** [comment]
I agree with @ulfalizer : tests that are cheap, reliable and have simple dependencies can be run always, it keeps things simpler and maintenance easier, i.e.: no "premature optimization".

For other tests the answer is always "it depends".
